authguard:
  server:
    port: 3200

  injection:
    packages: [ "com.authguard", "com.nexblocks.authguard" ]

  passwords:
    algorithm: scrypt
    scrypt:
      blockSize: 16
    conditions:
      minLength: 6

  apiKeys:
    type: "default"
    hash:
      algorithm: blake2b
      key: "this is a test key"

  jwt:
    algorithm: "HMAC256"
    privateKey: "keys/hmac256.pem"
    issuer: "AuthGuard"
    allowedAlgorithms: ["HMAC256"]
    trustedIssuers: ["self"]
    encryption:
      algorithm: "AES_CBC"
      privateKey: "keys/aes128.txt"

  sessions:
    randomSize: 16
    lifeTime: "30m"

  exchange:
    providers: [ "accessToken", "sessionToken" ]
    allowed:
      - from: "basic"
        to: "passwordless"
      - from: "passwordless"
        to: "oidc"
      - from: "refresh"
        to: "accessToken"
      - from: "basic"
        to: "accessToken"
      - from: "refresh"
        to: "accessToken"
      - from: "basic"
        to: "otp"
      - from: "basic"
        to: "sessionToken"
      - from: "sessionToken"
        to: "accountId"
      - from: "sessionToken"
        to: "session"
      - from: "basic"
        to: "oidc"
      - from: "encryptedToken"
        to: "accessToken"
      - from: "encryptedToken"
        to: "idToken"

  accessToken:
    tokenLife: "10m"
    refreshTokenLife: "1d"
    useJti: true
    includeRoles: true

  idToken:
    tokenLife: "1h"
    refreshTokenLife: "1d"
    useJti: true

  otp:
    lifeTime: "2m"
    mode: "NUMERIC"
    length: 6
    generateToken: "accessToken"

  passwordless:
    tokenLife: "10m"
    randomSize: 128
    generateToken: "oidc"

  authorizationCode:
    lifeTime: "5m"
    randomSize: 128

  authentication:
    generateToken: "accessToken"
    logoutToken: "accessToken"

  accounts:
    authguardAdminRole: "authguard_admin"
    verifyEmail: true

  apps:
    authguardAdminClientRole: "authguard_admin_client"

  verification:
    emailVerificationLife: "1d"

  external:
    email: true

  oneTimeAdmin:
    usernameVariable: "AUTHGUARD_OTA_USERNAME"
    passwordVariable: "AUTHGUARD_OTA_PASSWORD"

  emb:
    channels:
      - accounts
      - auth
      - verification
      - passwordless

  accountLocker:
    maxAttempt: 3

  mail:
    provider:
      fromAddress: noreply@authguard.com
      fromName: Tests
      templates:
        passwordless:
          file: emails/passwordless.hbs
          subject: Passwordless Yay
    javaMail:
      "mail.smtp.host": localhost
      "mail.smtp.port": 3125
      "mail.debug": true

