authguard:
  injection:
    packages: [ "com.authguard" ]

  passwords:
    algorithm: scrypt
    scrypt:
      blockSize: 16
    conditions:
#      includeCaps: true
      minLength: 6

  apiKeys:
    type: "default"

  jwt:
    algorithm: "HMAC256"
    privateKey: "FKvL11DI5rwgt51QgB3CVob3oWYrFNBzF0ROvu9Yaj8"
    issuer: "AuthGuard"
    allowedAlgorithms: ["HMAC256"]
    trustedIssuers: ["self"]

  exchange:
    allowed:
      - from: "basic"
        to: "accessToken"
      - from: "basic"
        to: "otp"

  accessToken:
    tokenLife: "1h"
    refreshTokenLife: "1d"
    useJti: true
    includePermissions: true
    includeRoles: true

  otp:
    lifeTime: "2m"
    mode: "NUMERIC"
    length: 6
    generateToken: "accessToken"

  passwordless:
    tokenLife: "1h"
    randomSize: 128
    generateToken: "accessToken"

  authorizationCode:
    lifeTime: "5m"
    randomSize: 128

  authentication:
    generateToken: "accessToken"

  accounts:
    authguardAdminRole: "authguard_admin"
    verifyEmail: true

  apps:
    authguardAdminClientRole: "authguard_admin_client"

#  verification:
#    verifyEmailUrlTemplate: "http://gateway/authguard/verify/email?token=${token}"
#    emailVerificationLife: "1d"

  oneTimeAdmin:
    usernameVariable: "AUTHGUARD_OTA_USERNAME"
    passwordVariable: "AUTHGUARD_OTA_PASSWORD"

  emb:
    channels:
      - accounts
      - auth
